[2024-04-18T05:06:55.148+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-18T05:06:55.181+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dagExtract.validateData scheduled__2024-04-18T03:30:00+00:00 [queued]>
[2024-04-18T05:06:55.202+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dagExtract.validateData scheduled__2024-04-18T03:30:00+00:00 [queued]>
[2024-04-18T05:06:55.228+0000] {taskinstance.py:2303} INFO - Starting attempt 3 of 3
[2024-04-18T05:06:55.252+0000] {taskinstance.py:2327} INFO - Executing <Task(BranchPythonOperator): validateData> on 2024-04-18 03:30:00+00:00
[2024-04-18T05:06:55.260+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=7790) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-18T05:06:55.262+0000] {standard_task_runner.py:63} INFO - Started process 7792 to run task
[2024-04-18T05:06:55.265+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dagExtract', 'validateData', 'scheduled__2024-04-18T03:30:00+00:00', '--job-id', '341', '--raw', '--subdir', 'DAGS_FOLDER/ExtractApi.py', '--cfg-path', '/tmp/tmp2jef2l5a']
[2024-04-18T05:06:55.268+0000] {standard_task_runner.py:91} INFO - Job 341: Subtask validateData
[2024-04-18T05:06:55.350+0000] {task_command.py:426} INFO - Running <TaskInstance: dagExtract.validateData scheduled__2024-04-18T03:30:00+00:00 [running]> on host 0761b779d565
[2024-04-18T05:06:55.502+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dagExtract' AIRFLOW_CTX_TASK_ID='validateData' AIRFLOW_CTX_EXECUTION_DATE='2024-04-18T03:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-18T03:30:00+00:00'
[2024-04-18T05:06:55.504+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-18T05:06:55.505+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-04-18T05:06:55.601+0000] {logging_mixin.py:188} INFO - Df Rows: 50
[2024-04-18T05:06:55.602+0000] {python.py:237} INFO - Done. Returned value was: persistData
[2024-04-18T05:06:55.602+0000] {branch.py:36} INFO - Branch into persistData
[2024-04-18T05:06:55.603+0000] {skipmixin.py:178} INFO - Following branch persistData
[2024-04-18T05:06:55.633+0000] {skipmixin.py:246} INFO - Skipping tasks [('exceptionData', -1)]
[2024-04-18T05:06:55.976+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-18T05:06:56.001+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=dagExtract, task_id=validateData, execution_date=20240418T033000, start_date=20240418T050655, end_date=20240418T050656
[2024-04-18T05:06:56.080+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-18T05:06:56.124+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-18T05:06:56.130+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
