[2024-04-17T04:23:42.124+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-17T04:23:42.155+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dagExtract.validateData scheduled__2024-04-17T02:30:00+00:00 [queued]>
[2024-04-17T04:23:42.164+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dagExtract.validateData scheduled__2024-04-17T02:30:00+00:00 [queued]>
[2024-04-17T04:23:42.165+0000] {taskinstance.py:2303} INFO - Starting attempt 3 of 3
[2024-04-17T04:23:42.187+0000] {taskinstance.py:2327} INFO - Executing <Task(BranchPythonOperator): validateData> on 2024-04-17 02:30:00+00:00
[2024-04-17T04:23:42.197+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=232) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-17T04:23:42.200+0000] {standard_task_runner.py:63} INFO - Started process 234 to run task
[2024-04-17T04:23:42.199+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dagExtract', 'validateData', 'scheduled__2024-04-17T02:30:00+00:00', '--job-id', '96', '--raw', '--subdir', 'DAGS_FOLDER/FirstDag.py', '--cfg-path', '/tmp/tmpvs562hkl']
[2024-04-17T04:23:42.201+0000] {standard_task_runner.py:91} INFO - Job 96: Subtask validateData
[2024-04-17T04:23:42.268+0000] {task_command.py:426} INFO - Running <TaskInstance: dagExtract.validateData scheduled__2024-04-17T02:30:00+00:00 [running]> on host 960ed0fb8e64
[2024-04-17T04:23:42.407+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dagExtract' AIRFLOW_CTX_TASK_ID='validateData' AIRFLOW_CTX_EXECUTION_DATE='2024-04-17T02:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-17T02:30:00+00:00'
[2024-04-17T04:23:42.412+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-17T04:23:42.413+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-04-17T04:23:42.497+0000] {logging_mixin.py:188} INFO - Df Size: 50
[2024-04-17T04:23:42.498+0000] {python.py:237} INFO - Done. Returned value was: <Task(PythonOperator): persistData>
[2024-04-17T04:23:42.501+0000] {branch.py:36} INFO - Branch into <Task(PythonOperator): persistData>
[2024-04-17T04:23:42.501+0000] {skipmixin.py:178} INFO - Following branch <Task(PythonOperator): persistData>
[2024-04-17T04:23:42.503+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-17T04:23:42.519+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 269, in execute
    return self.do_branch(context, super().execute(context))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/branch.py", line 37, in do_branch
    self.skip_all_except(context["ti"], branches_to_execute)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/skipmixin.py", line 194, in skip_all_except
    raise AirflowException(
airflow.exceptions.AirflowException: 'branch_task_ids' must be either None, a task ID, or an Iterable of IDs, but got 'PythonOperator'.
[2024-04-17T04:23:42.525+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=dagExtract, task_id=validateData, execution_date=20240417T023000, start_date=20240417T042342, end_date=20240417T042342
[2024-04-17T04:23:42.577+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 96 for task validateData ('branch_task_ids' must be either None, a task ID, or an Iterable of IDs, but got 'PythonOperator'.; 234)
[2024-04-17T04:23:42.616+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-17T04:23:42.670+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-17T04:23:42.678+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
