[2024-04-18T04:23:28.478+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-18T04:23:28.507+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dagOrchestration.validateData manual__2024-04-18T04:23:22.360220+00:00 [queued]>
[2024-04-18T04:23:28.517+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dagOrchestration.validateData manual__2024-04-18T04:23:22.360220+00:00 [queued]>
[2024-04-18T04:23:28.537+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-18T04:23:28.559+0000] {taskinstance.py:2327} INFO - Executing <Task(BranchPythonOperator): validateData> on 2024-04-18 04:23:22.360220+00:00
[2024-04-18T04:23:28.567+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=7071) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-18T04:23:28.569+0000] {standard_task_runner.py:63} INFO - Started process 7074 to run task
[2024-04-18T04:23:28.572+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dagOrchestration', 'validateData', 'manual__2024-04-18T04:23:22.360220+00:00', '--job-id', '327', '--raw', '--subdir', 'DAGS_FOLDER/DagOrchestration.py', '--cfg-path', '/tmp/tmplxz83wnx']
[2024-04-18T04:23:28.574+0000] {standard_task_runner.py:91} INFO - Job 327: Subtask validateData
[2024-04-18T04:23:28.650+0000] {task_command.py:426} INFO - Running <TaskInstance: dagOrchestration.validateData manual__2024-04-18T04:23:22.360220+00:00 [running]> on host 0761b779d565
[2024-04-18T04:23:28.773+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dagOrchestration' AIRFLOW_CTX_TASK_ID='validateData' AIRFLOW_CTX_EXECUTION_DATE='2024-04-18T04:23:22.360220+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-18T04:23:22.360220+00:00'
[2024-04-18T04:23:28.776+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-18T04:23:28.776+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-04-18T04:23:28.857+0000] {logging_mixin.py:188} INFO - Df Rows: 50
[2024-04-18T04:23:28.858+0000] {python.py:237} INFO - Done. Returned value was: persistData
[2024-04-18T04:23:28.859+0000] {branch.py:36} INFO - Branch into persistData
[2024-04-18T04:23:28.860+0000] {skipmixin.py:178} INFO - Following branch persistData
[2024-04-18T04:23:28.888+0000] {skipmixin.py:246} INFO - Skipping tasks [('exceptionData', -1)]
[2024-04-18T04:23:28.923+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-18T04:23:28.951+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=dagOrchestration, task_id=validateData, execution_date=20240418T042322, start_date=20240418T042328, end_date=20240418T042328
[2024-04-18T04:23:28.984+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-18T04:23:29.019+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-18T04:23:29.043+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
