[2024-04-16T01:19:24.493+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-16T01:19:24.521+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Tutorial_MALUCO.captura manual__2024-04-16T01:19:21.509854+00:00 [queued]>
[2024-04-16T01:19:24.531+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Tutorial_MALUCO.captura manual__2024-04-16T01:19:21.509854+00:00 [queued]>
[2024-04-16T01:19:24.629+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-16T01:19:24.662+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): captura> on 2024-04-16 01:19:21.509854+00:00
[2024-04-16T01:19:24.679+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=739) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-16T01:19:24.675+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Tutorial_MALUCO', 'captura', 'manual__2024-04-16T01:19:21.509854+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/FirstDag.py', '--cfg-path', '/tmp/tmp0t8rgg39']
[2024-04-16T01:19:24.681+0000] {standard_task_runner.py:63} INFO - Started process 747 to run task
[2024-04-16T01:19:24.681+0000] {standard_task_runner.py:91} INFO - Job 15: Subtask captura
[2024-04-16T01:19:24.909+0000] {task_command.py:426} INFO - Running <TaskInstance: Tutorial_MALUCO.captura manual__2024-04-16T01:19:21.509854+00:00 [running]> on host df00be3806a2
[2024-04-16T01:19:25.150+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Tutorial_MALUCO' AIRFLOW_CTX_TASK_ID='captura' AIRFLOW_CTX_EXECUTION_DATE='2024-04-16T01:19:21.509854+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-16T01:19:21.509854+00:00'
[2024-04-16T01:19:25.152+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-16T01:19:25.826+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-16T01:19:25.828+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/FirstDag.py", line 12, in captura
    df = pd.DataFrame(json.load(response.content))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
                 ^^^^^^^
AttributeError: 'bytes' object has no attribute 'read'
[2024-04-16T01:19:25.852+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=Tutorial_MALUCO, task_id=captura, execution_date=20240416T011921, start_date=20240416T011924, end_date=20240416T011925
[2024-04-16T01:19:25.873+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 15 for task captura ('bytes' object has no attribute 'read'; 747)
[2024-04-16T01:19:25.904+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-16T01:19:25.924+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-16T01:19:26.020+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
