[2024-04-16T01:04:04.602+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-16T01:04:04.630+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Tutorial_MALUCO.captura scheduled__2024-04-15T23:30:00+00:00 [queued]>
[2024-04-16T01:04:04.639+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Tutorial_MALUCO.captura scheduled__2024-04-15T23:30:00+00:00 [queued]>
[2024-04-16T01:04:04.743+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-16T01:04:04.777+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): captura> on 2024-04-15 23:30:00+00:00
[2024-04-16T01:04:04.786+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=543) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-16T01:04:04.789+0000] {standard_task_runner.py:63} INFO - Started process 547 to run task
[2024-04-16T01:04:04.789+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Tutorial_MALUCO', 'captura', 'scheduled__2024-04-15T23:30:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/FirstDag.py', '--cfg-path', '/tmp/tmpa6_b7hz2']
[2024-04-16T01:04:04.790+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask captura
[2024-04-16T01:04:04.861+0000] {task_command.py:426} INFO - Running <TaskInstance: Tutorial_MALUCO.captura scheduled__2024-04-15T23:30:00+00:00 [running]> on host df00be3806a2
[2024-04-16T01:04:05.059+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Tutorial_MALUCO' AIRFLOW_CTX_TASK_ID='captura' AIRFLOW_CTX_EXECUTION_DATE='2024-04-15T23:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-15T23:30:00+00:00'
[2024-04-16T01:04:05.061+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-16T01:04:05.319+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-16T01:04:05.320+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/FirstDag.py", line 11, in captura
    df = pd.DataFrame(json.load(response.content))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
                 ^^^^^^^
AttributeError: 'bytes' object has no attribute 'read'
[2024-04-16T01:04:05.338+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=Tutorial_MALUCO, task_id=captura, execution_date=20240415T233000, start_date=20240416T010404, end_date=20240416T010405
[2024-04-16T01:04:05.455+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 13 for task captura ('bytes' object has no attribute 'read'; 547)
[2024-04-16T01:04:05.486+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-16T01:04:05.515+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-16T01:04:05.520+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
