[2024-04-18T01:17:17.096+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-18T01:17:17.142+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dagPartition.output manual__2024-04-18T01:14:39.903288+00:00 [queued]>
[2024-04-18T01:17:17.157+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dagPartition.output manual__2024-04-18T01:14:39.903288+00:00 [queued]>
[2024-04-18T01:17:17.158+0000] {taskinstance.py:2303} INFO - Starting attempt 3 of 3
[2024-04-18T01:17:17.186+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): output> on 2024-04-18 01:14:39.903288+00:00
[2024-04-18T01:17:17.194+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3051) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-18T01:17:17.196+0000] {standard_task_runner.py:63} INFO - Started process 3060 to run task
[2024-04-18T01:17:17.200+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dagPartition', 'output', 'manual__2024-04-18T01:14:39.903288+00:00', '--job-id', '200', '--raw', '--subdir', 'DAGS_FOLDER/PartitionLocation.py', '--cfg-path', '/tmp/tmp67dzvjxk']
[2024-04-18T01:17:17.203+0000] {standard_task_runner.py:91} INFO - Job 200: Subtask output
[2024-04-18T01:17:17.275+0000] {task_command.py:426} INFO - Running <TaskInstance: dagPartition.output manual__2024-04-18T01:14:39.903288+00:00 [running]> on host 0761b779d565
[2024-04-18T01:17:17.419+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dagPartition' AIRFLOW_CTX_TASK_ID='output' AIRFLOW_CTX_EXECUTION_DATE='2024-04-18T01:14:39.903288+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-18T01:14:39.903288+00:00'
[2024-04-18T01:17:17.422+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-18T01:17:17.518+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-18T01:17:17.519+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/PartitionLocation.py", line 58, in PersistData
    df.to_parquet('datalake/silver', partition_cols=['country', 'state', 'city', 'dt_process'], compression='gzip')
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 2970, in to_parquet
    return to_parquet(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 483, in to_parquet
    impl.write(
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 216, in write
    self.api.parquet.write_to_dataset(
  File "/home/airflow/.local/lib/python3.12/site-packages/pyarrow/parquet/core.py", line 2143, in write_to_dataset
    part_schema = table.select(partition_cols).schema
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/table.pxi", line 3458, in pyarrow.lib.Table.select
  File "pyarrow/table.pxi", line 1561, in pyarrow.lib._Tabular._ensure_integer_index
KeyError: 'Field "dt_process" does not exist in schema'
[2024-04-18T01:17:17.540+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=dagPartition, task_id=output, execution_date=20240418T011439, start_date=20240418T011717, end_date=20240418T011717
[2024-04-18T01:17:17.558+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 200 for task output ('Field "dt_process" does not exist in schema'; 3060)
[2024-04-18T01:17:17.573+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-18T01:17:17.598+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-18T01:17:17.602+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
