[2024-04-18T03:49:47.733+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-18T03:49:47.788+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dagAggregation.vwCountry scheduled__2024-04-18T01:30:00+00:00 [queued]>
[2024-04-18T03:49:47.804+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dagAggregation.vwCountry scheduled__2024-04-18T01:30:00+00:00 [queued]>
[2024-04-18T03:49:47.805+0000] {taskinstance.py:2303} INFO - Starting attempt 8 of 8
[2024-04-18T03:49:47.828+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): vwCountry> on 2024-04-18 01:30:00+00:00
[2024-04-18T03:49:47.836+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=6578) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-18T03:49:47.838+0000] {standard_task_runner.py:63} INFO - Started process 6580 to run task
[2024-04-18T03:49:47.838+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dagAggregation', 'vwCountry', 'scheduled__2024-04-18T01:30:00+00:00', '--job-id', '322', '--raw', '--subdir', 'DAGS_FOLDER/AggData.py', '--cfg-path', '/tmp/tmpy3zff21_']
[2024-04-18T03:49:47.840+0000] {standard_task_runner.py:91} INFO - Job 322: Subtask vwCountry
[2024-04-18T03:49:47.914+0000] {task_command.py:426} INFO - Running <TaskInstance: dagAggregation.vwCountry scheduled__2024-04-18T01:30:00+00:00 [running]> on host 0761b779d565
[2024-04-18T03:49:48.299+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dagAggregation' AIRFLOW_CTX_TASK_ID='vwCountry' AIRFLOW_CTX_EXECUTION_DATE='2024-04-18T01:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='8' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-18T01:30:00+00:00'
[2024-04-18T03:49:48.301+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-18T03:49:48.421+0000] {warnings.py:110} WARNING - /opt/***/dags/AggData.py:44: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  vw_location = df.groupby(['country', 'state', 'city'])['id'].count().reset_index()

[2024-04-18T03:49:48.436+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-18T03:49:48.437+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/AggData.py", line 49, in GroupByCountry
    vw_location = vw_location.sort_values(by='number', ascending=False)
                  ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'sort_values'
[2024-04-18T03:49:48.454+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=dagAggregation, task_id=vwCountry, execution_date=20240418T013000, start_date=20240418T034947, end_date=20240418T034948
[2024-04-18T03:49:48.476+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 322 for task vwCountry ('list' object has no attribute 'sort_values'; 6580)
[2024-04-18T03:49:48.495+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-18T03:49:48.519+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-18T03:49:48.706+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
