[2024-04-17T01:32:59.634+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-17T01:32:59.674+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Tutorial_MALUCO.captura scheduled__2024-04-16T22:30:00+00:00 [queued]>
[2024-04-17T01:32:59.687+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Tutorial_MALUCO.captura scheduled__2024-04-16T22:30:00+00:00 [queued]>
[2024-04-17T01:32:59.733+0000] {taskinstance.py:2303} INFO - Starting attempt 11 of 11
[2024-04-17T01:32:59.760+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): captura> on 2024-04-16 22:30:00+00:00
[2024-04-17T01:32:59.771+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1012) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-17T01:32:59.774+0000] {standard_task_runner.py:63} INFO - Started process 1014 to run task
[2024-04-17T01:32:59.777+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Tutorial_MALUCO', 'captura', 'scheduled__2024-04-16T22:30:00+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/FirstDag.py', '--cfg-path', '/tmp/tmp_070qg_4']
[2024-04-17T01:32:59.780+0000] {standard_task_runner.py:91} INFO - Job 43: Subtask captura
[2024-04-17T01:32:59.970+0000] {task_command.py:426} INFO - Running <TaskInstance: Tutorial_MALUCO.captura scheduled__2024-04-16T22:30:00+00:00 [running]> on host 8dbfbc3d620a
[2024-04-17T01:33:00.361+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Tutorial_MALUCO' AIRFLOW_CTX_TASK_ID='captura' AIRFLOW_CTX_EXECUTION_DATE='2024-04-16T22:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='11' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-16T22:30:00+00:00'
[2024-04-17T01:33:00.364+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-17T01:33:00.660+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-17T01:33:00.662+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/FirstDag.py", line 16, in captura
    df.show()
    ^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 6204, in __getattr__
    return object.__getattribute__(self, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataFrame' object has no attribute 'show'
[2024-04-17T01:33:00.712+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=Tutorial_MALUCO, task_id=captura, execution_date=20240416T223000, start_date=20240417T013259, end_date=20240417T013300
[2024-04-17T01:33:00.815+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 43 for task captura ('DataFrame' object has no attribute 'show'; 1014)
[2024-04-17T01:33:00.875+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-17T01:33:00.916+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-17T01:33:00.963+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
