[2024-04-17T01:44:14.278+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-17T01:44:14.311+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Tutorial_MALUCO.captura scheduled__2024-04-16T22:30:00+00:00 [queued]>
[2024-04-17T01:44:14.334+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Tutorial_MALUCO.captura scheduled__2024-04-16T22:30:00+00:00 [queued]>
[2024-04-17T01:44:14.340+0000] {taskinstance.py:2303} INFO - Starting attempt 19 of 19
[2024-04-17T01:44:14.367+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): captura> on 2024-04-16 22:30:00+00:00
[2024-04-17T01:44:14.377+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1177) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-17T01:44:14.380+0000] {standard_task_runner.py:63} INFO - Started process 1179 to run task
[2024-04-17T01:44:14.380+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Tutorial_MALUCO', 'captura', 'scheduled__2024-04-16T22:30:00+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/FirstDag.py', '--cfg-path', '/tmp/tmp3iu4nshq']
[2024-04-17T01:44:14.382+0000] {standard_task_runner.py:91} INFO - Job 51: Subtask captura
[2024-04-17T01:44:14.450+0000] {task_command.py:426} INFO - Running <TaskInstance: Tutorial_MALUCO.captura scheduled__2024-04-16T22:30:00+00:00 [running]> on host 8dbfbc3d620a
[2024-04-17T01:44:14.583+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Tutorial_MALUCO' AIRFLOW_CTX_TASK_ID='captura' AIRFLOW_CTX_EXECUTION_DATE='2024-04-16T22:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='19' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-16T22:30:00+00:00'
[2024-04-17T01:44:14.585+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-17T01:44:14.735+0000] {logging_mixin.py:188} INFO - var type: <class 'requests.models.Response'>
[2024-04-17T01:44:14.736+0000] {logging_mixin.py:188} INFO - var type: <class 'list'>
[2024-04-17T01:44:14.737+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-17T01:44:14.738+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/FirstDag.py", line 18, in captura
    df = pd.DataFrame([[d['v'] for d in x['c']] for x in j['rows']],
                                                         ^
NameError: name 'j' is not defined
[2024-04-17T01:44:14.765+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=Tutorial_MALUCO, task_id=captura, execution_date=20240416T223000, start_date=20240417T014414, end_date=20240417T014414
[2024-04-17T01:44:14.783+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 51 for task captura (name 'j' is not defined; 1179)
[2024-04-17T01:44:14.796+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-17T01:44:14.822+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-17T01:44:14.833+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
