[2024-04-18T01:30:07.688+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-18T01:30:07.726+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dagExtract.validateData scheduled__2024-04-18T00:30:00+00:00 [queued]>
[2024-04-18T01:30:07.740+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dagExtract.validateData scheduled__2024-04-18T00:30:00+00:00 [queued]>
[2024-04-18T01:30:07.742+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-18T01:30:07.763+0000] {taskinstance.py:2327} INFO - Executing <Task(BranchPythonOperator): validateData> on 2024-04-18 00:30:00+00:00
[2024-04-18T01:30:07.776+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3345) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-18T01:30:07.780+0000] {standard_task_runner.py:63} INFO - Started process 3350 to run task
[2024-04-18T01:30:07.781+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dagExtract', 'validateData', 'scheduled__2024-04-18T00:30:00+00:00', '--job-id', '214', '--raw', '--subdir', 'DAGS_FOLDER/ExtractApi.py', '--cfg-path', '/tmp/tmpyu1lmxpc']
[2024-04-18T01:30:07.784+0000] {standard_task_runner.py:91} INFO - Job 214: Subtask validateData
[2024-04-18T01:30:07.858+0000] {task_command.py:426} INFO - Running <TaskInstance: dagExtract.validateData scheduled__2024-04-18T00:30:00+00:00 [running]> on host 0761b779d565
[2024-04-18T01:30:07.997+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dagExtract' AIRFLOW_CTX_TASK_ID='validateData' AIRFLOW_CTX_EXECUTION_DATE='2024-04-18T00:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-18T00:30:00+00:00'
[2024-04-18T01:30:07.999+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-18T01:30:08.001+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-04-18T01:30:08.101+0000] {logging_mixin.py:188} INFO - Df Rows: 50
[2024-04-18T01:30:08.102+0000] {python.py:237} INFO - Done. Returned value was: persistData
[2024-04-18T01:30:08.103+0000] {branch.py:36} INFO - Branch into persistData
[2024-04-18T01:30:08.104+0000] {skipmixin.py:178} INFO - Following branch persistData
[2024-04-18T01:30:08.132+0000] {skipmixin.py:246} INFO - Skipping tasks [('exceptionData', -1)]
[2024-04-18T01:30:08.179+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-18T01:30:08.210+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=dagExtract, task_id=validateData, execution_date=20240418T003000, start_date=20240418T013007, end_date=20240418T013008
[2024-04-18T01:30:08.277+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-18T01:30:08.319+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-18T01:30:08.369+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
